FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

ARG PROJECT_PATH
COPY ${PROJECT_PATH} service.csproj
RUN dotnet restore service.csproj

COPY . .
RUN dotnet publish ${PROJECT_PATH} -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:5000
ARG SERVICE_DLL=service.dll
ENV SERVICE_DLL=${SERVICE_DLL}
EXPOSE 5000

ENTRYPOINT ["sh", "-c", "dotnet ${SERVICE_DLL}"]
